version: "3.9"
services:
  dashboard:
    container_name: dashboard
    image: dashboard:dca-analyzer-with-postgres-and-s3
    volumes:
      - /home/dashboard/data:/home/drupman/PycharmProjects/contribution_projects/dashboard/data
    ports:
      - "8501:8501"
    env_file:
      - .env

  db:
    image: postgres:14
    ports:
      - "5480:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgres_password

volumes:
    db-data:

secrets:
  postgres_password:
    file: .env